GET http://localhost:3003/users

###
GET http://localhost:3003/api/blogs
###
POST http://localhost:3003/user
Content-Type: application/json

{
  "userName": "MewMew",
  "name": "Mew Mew Mew",
  "password": "1234568"
}

###
DELETE http://localhost:3003/api/blogs/65b04166ecd7e515599c3153

